version: "3"

tasks:
  build:
    dir: trynim
    cmds:
      - nimble build
  run:
    dir: trynim
    cmds:
      - nimble run
  test:
    dir: trynim
    cmds:
      - nimble test
  clean:
    dir: trynim
    cmds:
      - rm -f trynim
